  minimumCompressionSize: 1024
  shouldStartNameWithService: true
  apiKeys:
    - free: ${file(./customers.js):getUsersFreePlan}
    - paid: ${file(./customers.js):getUsersPaidPlan}
  usagePlan:
    - free:
        quota:
          limit: 5
          period: MONTH
        throttle:
          burstLimit: 200
          rateLimit: 200
    - paid:
        quota:
          limit: 1000
          period: DAY
        throttle:
          burstLimit: 400
          rateLimit: 50